### ISSUE TITLE
ftcli doesn't work as described

### ISSUE THREAD

**Issue by chri2** [YunoHost-Apps/fittrackee_ynh#67]
```
# pushd /var/www/fittrackee/
    source /var/www/fittrackee/venv/bin/activate
/var/www/fittrackee /usr/share/yunohost/hooks
(venv) root@yt:/var/www/fittrackee# ftcli --help
Traceback (most recent call last):
  File "/var/www/fittrackee/venv/bin/ftcli", line 5, in <module>
    from fittrackee.cli import cli
  File "/var/www/fittrackee/venv/lib/python3.9/site-packages/fittrackee/cli/__init__.py", line 3, in <module>
    from fittrackee.migrations.commands import db_cli
  File "/var/www/fittrackee/venv/lib/python3.9/site-packages/fittrackee/migrations/commands.py", line 9, in <module>
    from fittrackee.cli.app import app
  File "/var/www/fittrackee/venv/lib/python3.9/site-packages/fittrackee/cli/app.py", line 3, in <module>
    app = create_app(init_email=False)
  File "/var/www/fittrackee/venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 89, in create_app
    db.init_app(app)
  File "/var/www/fittrackee/venv/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 310, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.
```

There's missing instruction to set the necessary environment variables like

```
# export $(grep -v '^#' .env | xargs)
-bash: export: `<a': not a valid identifier
-bash: export: `noreferrer">OpenStreetMap</a>': not a valid identifier
```

which obviously is not perfect, but makes the command work.

**Comment by Thovi98** [comment]
Could you please confirm that https://github.com/YunoHost-Apps/fittrackee_ynh/pull/69 solves this issue?
