### ISSUE TITLE
Upgrade 0.8.7~ynh1 to 0.8.8~ynh1 failed

### ISSUE THREAD

**Issue by microniko** [YunoHost-Apps/fittrackee_ynh#77]
Mise à jour tentée : 
```
2024-09-09 22:24:41,125: DEBUG - + ynh_hide_warnings /var/www/fittrackee/venv/bin/ftcli db upgrade
2024-09-09 22:24:41,125: DEBUG - + /var/www/fittrackee/venv/bin/ftcli db upgrade
2024-09-09 22:24:41,705: DEBUG - Traceback (most recent call last):
2024-09-09 22:24:41,705: DEBUG -   File "/var/www/fittrackee/venv/bin/ftcli", line 5, in <module>
2024-09-09 22:24:41,705: DEBUG -     from fittrackee.cli import cli
2024-09-09 22:24:41,705: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/fittrackee/__init__.py", line 59, in <module>
2024-09-09 22:24:41,705: DEBUG -     r.ping()
2024-09-09 22:24:41,705: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/redis/commands/core.py", line 1205, in ping
2024-09-09 22:24:41,706: DEBUG -     return self.execute_command("PING", **kwargs)
2024-09-09 22:24:41,706: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/redis/client.py", line 1266, in execute_command
2024-09-09 22:24:41,706: DEBUG -     conn = self.connection or pool.get_connection(command_name, **options)
2024-09-09 22:24:41,706: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/redis/connection.py", line 1461, in get_connection
2024-09-09 22:24:41,706: DEBUG -     connection.connect()
2024-09-09 22:24:41,706: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/redis/connection.py", line 719, in connect
2024-09-09 22:24:41,706: DEBUG -     self.on_connect()
2024-09-09 22:24:41,706: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/redis/connection.py", line 784, in on_connect
2024-09-09 22:24:41,706: DEBUG -     if str_if_bytes(self.read_response()) != "OK":
2024-09-09 22:24:41,706: DEBUG -   File "/var/www/fittrackee/venv/lib/python3.9/site-packages/redis/connection.py", line 905, in read_response
2024-09-09 22:24:41,706: DEBUG -     raise response
2024-09-09 22:24:41,706: DEBUG - redis.exceptions.ResponseError: DB index is out of range
2024-09-09 22:24:41,775: DEBUG - + ynh_exit_properly
2024-09-09 22:24:41,775: DEBUG - + [[ upgrade =~ ^install$|^upgrade$|^restore$ ]]
2024-09-09 22:24:43,278: ERROR - Impossible de mettre à jour fittrackee : Une erreur s'est produite durant l'exécution du script de mise à niveau de l'application
```

Log complet : https://paste.yunohost.org/raw/rewimolivo

Merci ;-)

**Comment by Thovi98** [comment]
Mmh 🤔
Est-ce que tu peux me transmettre le résultat de `cat /etc/redis/redis.conf | grep ^databases` stp ?

**Comment by microniko** [comment]
Oui : 
```
root@microniko:~# cat /etc/redis/redis.conf | grep ^databases
databases 16
```

**Comment by Thovi98** [comment]
Je pense avoir trouvé le problème, peux-tu essayer la branche `testing`?

`sudo yunohost app upgrade fittrackee -u https://github.com/YunoHost-Apps/fittrackee_ynh/tree/testing --debug`

**Comment by microniko** [comment]
Pas mieux :-(

```
[…]
2024-09-18 22:55:50,441: WARNING - ./upgrade: ligne 28: redis_db : variable sans liaison
[…]
```
https://paste.yunohost.org/raw/wetiwiyofo

**Comment by Thovi98** [comment]
Est-ce que tu peux regarder ceci (https://forum.yunohost.org/t/fittrackee-self-hosted-outdoor-activity-tracker/24141/91?u=tho) ? 

C'est en anglais, dis-moi si tu veux que je traduise.

**Comment by microniko** [comment]
Merci, je lui à peu près l'anglais ;-)
Par contre, il me manque la commande `yq`. J'imagine que c'est cet [yq là](https://github.com/mikefarah/yq/) ?
L'idée de récupérer un binaire sur Github et l'exécuter en root me plait moyen ^_^
Y-aurait-il une alternative un peu plus _safe_ ?

**Comment by Thovi98** [comment]
Ah oui non c'est juste un `apt install yq` normalement :)

**Comment by Thovi98** [comment]
Ah oui, c'est parce que tu es encore sur Bullseye, j'oublie que Bookworm est encore en phase de test 😅

**Comment by microniko** [comment]
Il n'y a pas un autre moyen de lister les bases redis utilisées ?

**Comment by Thovi98** [comment]
Si sûrement, faut que je regarde.
Sinon tu sais lister tes apps installées ?

**Comment by Thovi98** [comment]
Ça m'a fait penser à une autre façon de voir les choses, bien plus facile 😄

Essaie ce script:

```
#!/bin/bash

# Get the list of all installed applications
apps=$(yunohost app list --output-as json | jq -r '.apps[].id')

# Loop through each application and get the redis_db setting
for app in $apps; do
    redis_db=$(yunohost app setting $app redis_db)
    echo "App: $app, Redis DB: $redis_db"
done
```

Il va lister chaque application installée et mentionner la valeur du redis_db (si d'application)

Après, il suffira de `flushdb` toutes les db non listées sauf 0. N'hésite pas à me transmettre ton résultat pour que je t'aide sur cette partie.

**Comment by microniko** [comment]
Merci @Thovi98 mais je ne vois pas de chiffre :interrobang: 

```
# bash redis_ynh.bash 
App: fittrackee, Redis DB: 
App: roundcube, Redis DB: 
App: rspamdui, Redis DB: 
App: vpnclient, Redis DB: 
```

**Comment by Thovi98** [comment]
Génial, ça veut dire que ton problème actuel ne vient que de FitTrackee (et de moi) 😇
Il ne te reste plus qu'à :

`redis-cli -n 1 FLUSHDB` et à faire de même en changeant à chaque fois le numéro jusqu'à 15.

Une fois que c'est fait, la mise à jour devrait pouvoir fonctionner sans soucis.

**Comment by microniko** [comment]
OK.
Merci, ça a fonctionné :+1: 

Mais comment sais-tu qu'il faut aller jusqu'à 15 ?!

**Comment by Thovi98** [comment]
Super ! Je me permets de fermer ce ticket alors :)

> Mais comment sais-tu qu'il faut aller jusqu'à 15 ?!

Grâce à ceci :

> root@microniko:~# cat /etc/redis/redis.conf | grep ^databases
> databases 16

Il faut compter le nombre donné -1.
